### ISSUE TITLE
Update packagist after the redirect

### ISSUE THREAD

**Issue by micc83** [klein-framework/klein.php#320]
Packagist hasn't been updated after the redirect...

**Comment by steadweb** [comment]
+1

**Comment by steadweb** [comment]
Add the following to your `composer.json` for a temporary workaround /cc @micc83 

```
    "repositories": [
        {   
            "type": "git",
            "url": "git@github.com:klein-framework/klein.php.git"
        }   
    ]
```

**Comment by micc83** [comment]
@steadweb Unfortunately I can't, I'm relying on dist version as the target machine doesn't comes with Git. :cry:

**Comment by steadweb** [comment]
Ah, you can use `https` instead and use the `--prefer-dist` flag with composer.

```
    "repositories": [
        {   
            "type": "vcs",
            "url": "https://github.com/klein-framework/klein.php.git"
        }   
    ], 
```

Composer command:

```
composer install --perfer-dist
```

Hopefully that should work for you :smile:

**Comment by micc83** [comment]
Unfortunately no luck.

My `composer.json` :

```json
{
  "repositories": [
    {   
      "type": "vcs",
      "url": "https://github.com/klein-framework/klein.php.git"
    }   
  ],
  "require": {
    "klein-framework/klein.php": "2.1.0"
  }
}
```

When I run:

```bash
$ php composer.phar update --prefer-dist
```

I get:

```
The requested package klein-framework/klein.php could not be found in any version, there may be a typo in the package name.
```

**Comment by steadweb** [comment]
Revert the change within the `require` as the package name hasn't changed, it's just the URL :smile: - So you want to require `"klein/klein": "2.1.0"` not `"klein-framework/klein.php": "2.1.0"`

Try the following:

```
{
  "repositories": [
    {   
      "type": "vcs",
      "url": "https://github.com/klein-framework/klein.php.git"
    }   
  ]
  "require": {
    "klein/klein": "2.1.0"
  }
}
```

Then run 

```
$ php composer.phar update --prefer-dist
```

**Comment by micc83** [comment]
Thank you @steadweb . I din't realize that the composer.json file of the package didn't changed either.

**Comment by steadweb** [comment]
No worries @micc83 :+1:

**Comment by Rican7** [comment]
Sorry about the inconvenience here, everyone.
We'll get this squared away **very** soon. It's breaking CI builds for me also. :stuck_out_tongue_closed_eyes:

**Comment by chriso** [comment]
https://github.com/chriso/klein.php should now redirect here.

**Comment by Rican7** [comment]
Just updated the Packagist repo URL :smiley: 
https://packagist.org/packages/klein/klein

Again, sorry for the inconvenience. :wave:
